# Generated by Django 3.2.4 on 2021-07-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resume_my_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.PositiveIntegerField(max_length=12),
        ),
    ]
