# Generated by Django 3.1.5 on 2021-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancledorders',
            name='bank_acc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='returnorders',
            name='bank_acc',
            field=models.CharField(max_length=50),
        ),
    ]
