# Generated by Django 3.2.4 on 2021-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptops'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('BG', 'Bag'), ('HP', 'HeadPhone'), ('W', 'Watches'), ('S', 'Shoes')], max_length=2),
        ),
    ]
