# Generated by Django 3.1.5 on 2021-07-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210720_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancledorders',
            name='reason',
            field=models.CharField(choices=[('ORDER_MISTAKE', 'ORDER_CREATED_BY_MISTAKE'), ('NOT_ARRIVED_TIME', 'ITEM NOT ARRIVED ON TIME'), ('S_HIGH_COST', 'SHIPPING COST TOO HIGH'), ('I_HIGH_COST', 'ITEM COST TOO HIGH'), ('FOUND_CHEAPER', 'FOUND CHEAPER SOMEWHERE ELSE'), ('CHANGE_S_ADDRESS', 'NEED TO CHANGE SHIPPING ADDRESS'), ('CHANGE_S_SPEED', 'NEED TO CHANGE SHIPPING SPEED'), ('CHANGE_BILLING_ADDRESS', 'NEED TO CHANGE BILLING ADDRESS'), ('CHANGE_PAYMETHOD', 'NEED TO CHANGE PAYMENT METHOD'), ('OTHER', 'OTHER')], default='Please Select One', max_length=50),
        ),
    ]
