# Generated by Django 3.2.4 on 2021-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSummerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptops'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('BG', 'Bag'), ('HP', 'HeadPhone'), ('W', 'Watches'), ('S', 'Shoes')], max_length=2)),
                ('product_image', models.ImageField(upload_to='productImg')),
            ],
            options={
                'db_table': 'ProductSummerNote',
            },
        ),
    ]
