# Generated by Django 3.2.4 on 2021-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productsummernote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSummerNote',
        ),
    ]
