# Generated by Django 3.1.5 on 2021-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210720_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorders',
            name='bank_name',
            field=models.CharField(choices=[('State Bank of India (SBI)', 'State Bank of India (SBI)'), ('Punjab National Bank', 'Punjab National Bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Canara Bank', 'Canara Bank'), ('Union Bank of India', 'Union Bank of India'), ('Bank of India', 'Bank of India'), ('Indian Bank', 'Indian Bank'), ('Central Bank of India', 'Central Bank of India'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('UCO Bank', 'UCO Bank'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Punjab & Sindh Bank', 'Punjab & Sindh Bank'), ('Axis', 'Axis'), ('Bandhan', 'Bandhan'), ('HDFC', 'HDFC'), ('ICICI', 'ICICI'), ('IDBI', 'IDBI'), ('Kotak Mahindra', 'Kotak Mahindra'), ('South Indian Bank', 'South Indian Bank'), ('Yes Bank', 'Yes Bank'), ('IndusInd Bank', 'IndusInd Bank')], max_length=50),
        ),
        migrations.AlterField(
            model_name='returnorders',
            name='rreason',
            field=models.CharField(choices=[('BAD_QUALITY', 'ORDER_CREATED_BY_MISTAKE'), ('PRODUCT_DAMAGE', 'ITEM NOT ARRIVED ON TIME'), ('MISSING_PART', 'SHIPPING COST TOO HIGH'), ('PRODUCT_AND_BOX_DAMAGE', 'ITEM COST TOO HIGH'), ('WRONG_ITEM_SEND', 'FOUND CHEAPER SOMEWHERE ELSE'), ('ITEM_DEFECTIVE', 'NEED TO CHANGE SHIPPING ADDRESS'), ('OTHER', 'OTHER')], max_length=150),
        ),
    ]
