# Generated by Django 3.2.4 on 2021-06-24 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), help_text='Today Date.', null=True),
        ),
    ]
